// <auto-generated />
using System;
using Ajuda.API;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Ajuda.API.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250607043513_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Ajuda.API.Models.PedidoAjuda", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DataHoraPedido")
                        .HasColumnType("datetime2")
                        .HasColumnName("DATA_HORA_PEDIDO");

                    b.Property<string>("Endereco")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("ENDERECO");

                    b.Property<int>("NivelUrgencia")
                        .HasColumnType("int")
                        .HasColumnName("NIVEL_URGENCIA");

                    b.Property<int>("QuantidadePessoas")
                        .HasColumnType("int")
                        .HasColumnName("QUANTIDADE_PESSOAS");

                    b.Property<int>("TipoAjudaId")
                        .HasColumnType("int")
                        .HasColumnName("TIPO_AJUDA_ID");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("int")
                        .HasColumnName("USUARIO_ID");

                    b.HasKey("Id");

                    b.HasIndex("TipoAjudaId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("TB_PEDIDO_AJUDA", (string)null);
                });

            modelBuilder.Entity("Ajuda.API.Models.TipoAjuda", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("DESCRICAO");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("NOME");

                    b.HasKey("Id");

                    b.ToTable("TB_TIPO_AJUDA", (string)null);
                });

            modelBuilder.Entity("Ajuda.API.Models.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("EhVoluntario")
                        .HasColumnType("int")
                        .HasColumnName("EH_VOLUNTARIO");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("EMAIL");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("NOME");

                    b.Property<string>("Telefone")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("TELEFONE");

                    b.HasKey("Id");

                    b.ToTable("TB_USUARIO", (string)null);
                });

            modelBuilder.Entity("Ajuda.API.Models.PedidoAjuda", b =>
                {
                    b.HasOne("Ajuda.API.Models.TipoAjuda", "TipoAjuda")
                        .WithMany()
                        .HasForeignKey("TipoAjudaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Ajuda.API.Models.Usuario", "Usuario")
                        .WithMany("PedidosAjuda")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TipoAjuda");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("Ajuda.API.Models.Usuario", b =>
                {
                    b.Navigation("PedidosAjuda");
                });
#pragma warning restore 612, 618
        }
    }
}
